### PR TITLE
Add optional constructor to permit initialization of struct properties.

### PR DESCRIPTION
**Pull request by jseibert**

### CODE REVIEW

**Comment by wickwirew** [comment]
Thanks for the PR! But would you mind providing a use case for this? I'm Interested to see how this would be used.

**Comment by sportlabsMike** [comment]
Hi @wickwirew 
This solves issue of trying to construct Struct types that contain properties that can't be handled by the current implementation of `func defaultValue(of type: Any.Type) throws -> Any {`
A specific common case we've come across is a Struct containing a simple Enum.
eg
````
enum MyEnum { case a, b }  
struct MyStruct {  
    let e: MyEnum
}
````

**Comment by wickwirew** [comment]
@sportlabsMike for that case you can tell Runtime how to create the enum by implementing the `DefaultConstructor` protocol.

Example:
```swift
enum MyEnum: DefaultConstructor {
    case a, b
    init() {
        self = .a
    }
}
```

**Comment by jseibert** [comment]
@wickwirew that will not work for values that are `let` members, because they can't then be overwritten with the correct value.

**Comment by jseibert** [comment]
That might work, but it permits less customization in the event a property is missing or of the wrong type. Check out: https://github.com/jseibert/GraphQL/blob/f29ae461718039036e73939020ceb8282ea3a285/Sources/GraphQL/Map/MapInitializable.swift

**Comment by jseibert** [comment]
And the discussion here for more context: https://github.com/GraphQLSwift/GraphQL/issues/37

**Comment by wickwirew** [comment]
Alright, I’ll go ahead and merge it in once I’m back at my computer. Should be an hour or so. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wickwirew** [comment]
All in!

**Comment by jseibert** [comment]
Woot! Thanks!

**Pull request merged**
