### PR TITLE
Framework/Test Targets for macOS

### PR DESCRIPTION
**Pull request by helje5**
I hope those do not confuse the Cocoapod.

This stuff makes it build as a Cocoa framework. Building things works fine, but the tests actually crash on macOS (same w/ `spm test` btw).

### CODE REVIEW

**Comment by wickwirew** [comment]
What test fails? Is it the create class in the issue you made?

**Comment by helje5** [comment]
Check issue #5. This is not related to Linux, it is just the same tests you run on iOS, fail on macOS. Seems to be an RC issue.

This PR is just adding a target to the Xcode project to build a macOS framework & tests. It should be fine to merge, unless they break the pods, don't know how that works.

**Comment by wickwirew** [comment]
I think I may be reverting the SPM stuff so I'm going to hold off. Not a big fan of the massive restructure. When I first looked over the PR it didn't show all the the moved files and only showed about 400 line changes but once merged I saw the full extent of the changes. My mind was also clouded by excitement of my first contributor lol. I think all of the changes minus the file restructure are good and we need them in but I would like to keep the project structure the same. In swift 4 they did a full redesign of the SPM and I believe now you don't have to have all of the `/Sources` folder. Take a look at ReSwift and they support SPM but have a normal more traditional fire structure. Sorry about all of the confusion this is my first open source project people want to contribute to so this is all new to me, and just trying to make sure everything is clean.

**Comment by helje5** [comment]
Hey, no problem, it's your very own project! ;-) I'm not entirely sure where you see a "massive restructure", the files just got moved into Sources/Tests, thats it, but sure, if you don't like it, there is no obligation to accept PRs :-)

**Comment by wickwirew** [comment]
Awesome thanks for being nice about it 🙂 I felt bad lol. Anxiety and OCD get the best of me. But I made a new `develop` and added the Package.swift and it builds fine for a test project as a dependency. So if you want to start fresh and branch off that and copy some of the changes for linux/test over that would be good.

**Comment by helje5** [comment]
BTW: This PR #4 is completely unrelated to SPM or Linux. It is about adding a regular macOS Target to the regular Xcode project you have. Do you want this? I think it would be good to get it working on macOS first, and then checkout Linux. I think it would be good to have at least a `cannotCreateInstanceOnThisPlatform` error.

(also: I'm personally fine w/ not having instance construction, I'm mostly interested in property write access, which does seem to work fine across platforms).

**Comment by helje5** [comment]
Anyways, if you reverted the directory structure, this would need an update, so do not commit merge yet ;-)

**Comment by helje5** [comment]
Actually, let me close this, I'm going to create a new PR.

**Pull request closed without merging**
